import { useState, useEffect } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import {
  FileText, Download, Trash2, Clock, TrendingUp,
  ChevronDown, ChevronUp, BarChart2, Scale, BookOpen,
  AlertTriangle, CheckCircle, Lightbulb, RefreshCw
} from 'lucide-react'
import toast from 'react-hot-toast'
import { reportsApi } from '../api/client'
import { useAuth } from '../context/AuthContext'
import ScoreGauge from '../components/ScoreGauge'
import LoadingSpinner from '../components/LoadingSpinner'
import Sidebar from '../components/Sidebar'

function scoreColor(s) {
  if (s == null) return 'text-slate-400'
  if (s >= 65) return 'text-emerald-400'
  if (s >= 40) return 'text-yellow-400'
  return 'text-coral-500'
}

function Section({ title, icon: Icon, iconClass, children, defaultOpen = false }) {
  const [open, setOpen] = useState(defaultOpen)
  return (
    <div className="glass-card overflow-hidden">
      <button onClick={() => setOpen(o => !o)}
        className="w-full flex items-center justify-between px-5 py-4 hover:bg-white/2 transition-colors text-left"
        aria-expanded={open}>
        <div className="flex items-center gap-2.5">
          <Icon className={`w-4 h-4 ${iconClass}`} />
          <span className="font-semibold text-sm text-white">{title}</span>
        </div>
        {open ? <ChevronUp className="w-4 h-4 text-slate-500" /> : <ChevronDown className="w-4 h-4 text-slate-500" />}
      </button>
      <AnimatePresence initial={false}>
        {open && (
          <motion.div
            key="body"
            initial={{ height: 0, opacity: 0 }}
            animate={{ height: 'auto', opacity: 1 }}
            exit={{ height: 0, opacity: 0 }}
            transition={{ duration: 0.25 }}
            style={{ overflow: 'hidden' }}
          >
            <div className="px-5 pb-5 pt-1 border-t border-white/5">{children}</div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  )
}

function List({ items = [], icon: Icon = CheckCircle, iconClass = 'text-brand-400' }) {
  if (!items?.length) return <p className="text-xs text-slate-500">None</p>
  return (
    <ul className="space-y-1.5 mt-2">
      {items.map((x, i) => (
        <li key={i} className="flex items-start gap-2 text-sm text-slate-300">
          <Icon className={`w-3.5 h-3.5 ${iconClass} mt-0.5 flex-shrink-0`} />
          <span>{x}</span>
        </li>
      ))}
    </ul>
  )
}

function buildMarkdown(report) {
  const a = report.genai_analysis || {}
  const p = report.profile || {}
  const score = report.feasibility_score || 0
  return `# TrustEval Trust Report
**Report ID:** ${report.id} · **Date:** ${new Date(report.created_at).toLocaleString()}

---

## 1. Startup Summary
- **Idea:** ${report.startup_idea}
- **Domain:** ${a.domain_classification || 'N/A'}
- **Feasibility Score:** ${score?.toFixed(2)}%
- **Assessment:** ${report.feasibility_label}

### AI Understanding
${a.what_ai_understood || ''}

### Executive Summary
${a.startup_summary || ''}

---

## 2. Domain & Research Analysis
- **Research Saturation:** ${a.research_saturation || 'N/A'}

### Research Gaps
${(a.research_gaps || []).map(g => `- ${g}`).join('\n')}

### Innovation Opportunities
${(a.innovation_opportunities || []).map(o => `- ${o}`).join('\n')}

---

## 3. Feasibility Assessment
- **Technical:** ${a.technical_feasibility || 'N/A'}
- **Market:** ${a.market_feasibility || 'N/A'}
- **Business:** ${a.business_feasibility || 'N/A'}

### Advantages
${(a.advantages || []).map(x => `- ${x}`).join('\n')}

### Risks
${(a.risks || []).map(x => `- ${x}`).join('\n')}

---

## 4. Implementation Plan
- **Timeline:** ${a.development_time_months || '?'} months
- **Budget:** ₹${(a.budget_inr || 0).toLocaleString('en-IN')}
- **Team Roles:** ${(a.team_roles || []).join(', ')}

---

## 5. Founder Profile (Protected Attributes)
| Attribute | Value |
|---|---|
| Gender | ${p.gender === 1 ? 'Male' : 'Female'} |
| Location | ${p.founder_location === 1 ? 'Urban' : 'Rural'} |
| Education | ${p.education_level === 1 ? 'Tier 1' : 'Tier 2/3'} |
| Funding Access | ${p.funding_access === 1 ? 'High' : 'Low'} |

---

*Generated by TrustEval — Explainable & Bias-Aware AI Framework*
`
}

export default function ReportsPage() {
  const { isAuthenticated } = useAuth()
  const [history, setHistory]   = useState([])
  const [loading, setLoading]   = useState(false)
  const [selected, setSelected] = useState(null)
  const [detail, setDetail]     = useState(null)
  const [detailLoading, setDL]  = useState(false)
  const [activeReport, setActiveReport] = useState(null)

  const fetchHistory = async () => {
    setLoading(true)
    try {
      const { data } = await reportsApi.history()
      setHistory(data)
    } catch {
      toast.error('Could not load reports')
    } finally {
      setLoading(false)
    }
  }

  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(() => {
    if (isAuthenticated) fetchHistory()
  }, [isAuthenticated])

  const selectReport = async (id) => {
    setSelected(id)
    setActiveReport(id)
    setDL(true)
    setDetail(null)
    try {
      const { data } = await reportsApi.get(id)
      setDetail(data)
    } catch {
      toast.error('Failed to load report')
    } finally {
      setDL(false)
    }
  }

  const deleteReport = async (id) => {
    try {
      await reportsApi.delete(id)
      setHistory(h => h.filter(r => r.id !== id))
      if (selected === id) { setSelected(null); setDetail(null) }
      toast.success('Deleted')
    } catch {
      toast.error('Delete failed')
    }
  }

  const downloadReport = () => {
    if (!detail) return
    const md = buildMarkdown(detail)
    const blob = new Blob([md], { type: 'text/markdown' })
    const url  = URL.createObjectURL(blob)
    const a    = document.createElement('a')
    a.href     = url
    a.download = `trusteval-report-${detail.id}.md`
    a.click()
    URL.revokeObjectURL(url)
    toast.success('Report downloaded')
  }

  const analysis = detail?.genai_analysis || {}

  return (
    <div className="flex h-full">
      <Sidebar onSelectReport={selectReport} activeReportId={activeReport} />

      <main className="flex-1 overflow-y-auto scroll-area">
        <div className="max-w-5xl mx-auto px-4 sm:px-6 py-8">
          <div className="flex items-center justify-between mb-6">
            <div>
              <h1 className="text-2xl font-display font-bold text-white">Trust Reports</h1>
              <p className="text-sm text-slate-400 mt-1">View, download and manage your evaluation history.</p>
            </div>
            <button onClick={fetchHistory}
              className="flex items-center gap-1.5 text-xs text-slate-400 hover:text-white transition-colors">
              <RefreshCw className={`w-3.5 h-3.5 ${loading ? 'animate-spin' : ''}`} />
              Refresh
            </button>
          </div>

          {!isAuthenticated ? (
            <div className="glass-card p-12 text-center">
              <p className="text-slate-400">Sign in to view your reports.</p>
            </div>
          ) : loading ? (
            <div className="glass-card p-12 flex justify-center">
              <LoadingSpinner size="lg" label="Loading reports…" />
            </div>
          ) : history.length === 0 ? (
            <div className="glass-card p-12 text-center">
              <FileText className="w-10 h-10 text-slate-600 mx-auto mb-3" />
              <p className="text-slate-400">No reports yet. Run an evaluation to generate your first report.</p>
            </div>
          ) : (
            <div className="grid lg:grid-cols-5 gap-5">
              {/* Report list */}
              <div className="lg:col-span-2 space-y-2">
                {history.map((r, i) => (
                  <motion.div
                    key={r.id}
                    initial={{ opacity: 0, x: -12 }}
                    animate={{ opacity: 1, x: 0 }}
                    transition={{ delay: i * 0.04 }}
                    onClick={() => selectReport(r.id)}
                    className={`group glass-card p-4 cursor-pointer transition-all duration-150
                      ${selected === r.id ? 'border-brand-500/30 bg-brand-500/5' : 'hover:border-white/12'}`}
                  >
                    <div className="flex items-start justify-between gap-2">
                      <p className="text-sm font-medium text-white line-clamp-2 flex-1">
                        {r.startup_idea?.slice(0, 60)}…
                      </p>
                      <button
                        onClick={(e) => { e.stopPropagation(); deleteReport(r.id) }}
                        className="opacity-0 group-hover:opacity-100 p-1 text-slate-500 hover:text-coral-400 transition-all"
                        aria-label="Delete report"
                      >
                        <Trash2 className="w-3.5 h-3.5" />
                      </button>
                    </div>
                    <div className="flex items-center gap-3 mt-2 flex-wrap">
                      {r.domain && <span className="tag text-[10px] py-0.5 px-2">{r.domain}</span>}
                      {r.feasibility_score != null && r.feasibility_score > 0 && (
                        <span className={`text-xs font-bold ${scoreColor(r.feasibility_score)}`}>
                          {r.feasibility_score.toFixed(1)}%
                        </span>
                      )}
                      {(r.feasibility_score == null || r.feasibility_score === 0) && r.feasibility_label && (
                        <span className="text-[10px] font-semibold text-slate-500 truncate max-w-[80px]">
                          {r.feasibility_label}
                        </span>
                      )}
                      <span className="text-[10px] text-slate-600 ml-auto flex items-center gap-1">
                        <Clock className="w-3 h-3" />
                        {new Date(r.created_at).toLocaleDateString()}
                      </span>
                    </div>
                  </motion.div>
                ))}
              </div>

              {/* Detail panel */}
              <div className="lg:col-span-3">
                {!selected && (
                  <div className="glass-card p-12 text-center h-full flex items-center justify-center">
                    <div>
                      <FileText className="w-8 h-8 text-slate-600 mx-auto mb-2" />
                      <p className="text-sm text-slate-500">Select a report to view details</p>
                    </div>
                  </div>
                )}

                {detailLoading && (
                  <div className="glass-card p-12 flex justify-center">
                    <LoadingSpinner size="lg" label="Loading report…" />
                  </div>
                )}

                {detail && !detailLoading && (
                  <motion.div initial={{ opacity: 0, x: 16 }} animate={{ opacity: 1, x: 0 }} className="space-y-4">
                    {/* Header card */}
                    <div className="glass-card p-5">
                      <div className="flex items-start justify-between gap-4 mb-4">
                        <div className="flex-1 min-w-0">
                          <p className="text-xs text-slate-500 mb-1">Report #{detail.id}</p>
                          <h2 className="text-sm font-semibold text-white line-clamp-3">{detail.startup_idea}</h2>
                          {detail.domain && <span className="tag mt-2">{detail.domain}</span>}
                        </div>
                        {/* Use genai_analysis score as fallback when ML score is null/zero */}
                        {(() => {
                          const score = (detail.feasibility_score && detail.feasibility_score > 0)
                            ? detail.feasibility_score
                            : (detail.genai_analysis?.feasibility_score || 0)
                          const label = detail.feasibility_label ||
                            detail.genai_analysis?.feasibility_label ||
                            detail.genai_analysis?.idea_novelty_status || ''
                          return <ScoreGauge score={score} label={label} size={90} />
                        })()}
                      </div>
                      <div className="flex gap-3">
                        <button onClick={downloadReport}
                          className="btn-primary flex items-center gap-2 text-xs py-2">
                          <Download className="w-3.5 h-3.5" />
                          Download .md
                        </button>
                      </div>
                    </div>

                    {/* Sections */}
                    <Section title="AI Understanding" icon={BookOpen} iconClass="text-brand-400" defaultOpen>
                      <p className="text-sm text-slate-300 leading-relaxed mt-2">{analysis.startup_summary}</p>
                      {analysis.keywords?.length > 0 && (
                        <div className="flex flex-wrap gap-1.5 mt-3">
                          {analysis.keywords.map((k, i) => <span key={i} className="tag text-[10px]">{k}</span>)}
                        </div>
                      )}
                    </Section>

                    <Section title="Research Analysis" icon={BarChart2} iconClass="text-violet-400">
                      <div className="space-y-4 mt-2">
                        <div>
                          <p className="text-xs font-semibold text-slate-400 mb-1">Research Saturation</p>
                          <span className={`tag ${analysis.research_saturation?.includes('saturated') ? 'tag-coral' : 'tag-green'}`}>
                            {analysis.research_saturation}
                          </span>
                        </div>
                        <div>
                          <p className="text-xs font-semibold text-slate-400 mb-1">Research Gaps</p>
                          <List items={analysis.research_gaps} icon={AlertTriangle} iconClass="text-coral-400" />
                        </div>
                        <div>
                          <p className="text-xs font-semibold text-slate-400 mb-1">Innovation Opportunities</p>
                          <List items={analysis.innovation_opportunities} icon={Lightbulb} iconClass="text-amber-400" />
                        </div>
                      </div>
                    </Section>

                    <Section title="Feasibility Report" icon={TrendingUp} iconClass="text-emerald-400">
                      <div className="grid grid-cols-3 gap-3 mt-2">
                        {[['Technical', analysis.technical_feasibility], ['Market', analysis.market_feasibility], ['Business', analysis.business_feasibility]].map(([k, v]) => (
                          <div key={k} className="p-3 rounded-xl bg-white/3 border border-white/5">
                            <p className="text-[10px] font-semibold text-slate-400 mb-1">{k}</p>
                            <p className="text-xs text-slate-300 leading-relaxed">{v || 'N/A'}</p>
                          </div>
                        ))}
                      </div>
                      <div className="grid sm:grid-cols-2 gap-4 mt-3">
                        <div>
                          <p className="text-xs font-semibold text-slate-400 mb-1">Advantages</p>
                          <List items={analysis.advantages} icon={CheckCircle} iconClass="text-emerald-400" />
                        </div>
                        <div>
                          <p className="text-xs font-semibold text-slate-400 mb-1">Risks</p>
                          <List items={analysis.risks} icon={AlertTriangle} iconClass="text-coral-400" />
                        </div>
                      </div>
                    </Section>

                    <Section title="Implementation Plan" icon={Clock} iconClass="text-amber-400">
                      <div className="grid grid-cols-3 gap-3 mt-2">
                        <div className="glass-card p-3 text-center">
                          <p className="text-[10px] text-slate-400">Timeline</p>
                          <p className="text-base font-bold text-white">{analysis.development_time_months}<span className="text-xs text-slate-400">mo</span></p>
                        </div>
                        <div className="glass-card p-3 text-center">
                          <p className="text-[10px] text-slate-400">Budget</p>
                          <p className="text-sm font-bold text-white">₹{(analysis.budget_inr||0).toLocaleString('en-IN')}</p>
                        </div>
                        <div className="glass-card p-3 text-center">
                          <p className="text-[10px] text-slate-400">Roles</p>
                          <p className="text-base font-bold text-white">{(analysis.team_roles||[]).length}</p>
                        </div>
                      </div>
                    </Section>

                    <Section title="Founder Profile (Protected Attributes)" icon={Scale} iconClass="text-coral-400">
                      {detail.profile ? (
                        <div className="grid grid-cols-2 gap-3 mt-2">
                          {[
                            ['Gender', detail.profile.gender === 1 ? 'Male' : 'Female'],
                            ['Location', detail.profile.founder_location === 1 ? 'Urban' : 'Rural'],
                            ['Education', detail.profile.education_level === 1 ? 'Tier 1' : 'Tier 2/3'],
                            ['Funding', detail.profile.funding_access === 1 ? 'High' : 'Low'],
                          ].map(([k, v]) => (
                            <div key={k} className="flex items-center justify-between px-3 py-2 rounded-lg bg-coral-500/5 border border-coral-500/10">
                              <span className="text-xs text-slate-400">{k}</span>
                              <span className="text-xs font-semibold text-coral-300">{v}</span>
                            </div>
                          ))}
                        </div>
                      ) : <p className="text-xs text-slate-500 mt-2">Profile data not available</p>}
                    </Section>
                  </motion.div>
                )}
              </div>
            </div>
          )}
        </div>
      </main>
    </div>
  )
}
